# Generated by Django 4.2.30 on 2026-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='name',
        ),
        migrations.AddField(
            model_name='division',
            name='div_name',
            field=models.CharField(default=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='in_scope',
            field=models.BooleanField(default=False, help_text='If the division is target for the learning program, check this field.'),
            preserve_default=False,
        ),
    ]
