# Generated by Django 4.2.30 on 2026-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0003_personalinfo_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='div_name',
            field=models.CharField(max_length=255),
        ),
    ]
