# Generated by Django 4.2.30 on 2026-09-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0004_alter_division_div_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcourse',
            name='employee',
            field=models.ManyToManyField(related_name='courses', to='employee_learning.employee', verbose_name='Employees following this course'),
        ),
    ]
