# Generated by Django 4.2.30 on 2026-09-08 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0005_alter_learningcourse_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='div_name',
            field=models.CharField(max_length=100, verbose_name='Nom de la division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='in_scope',
            field=models.BooleanField(default=False, help_text='La division est-elle concernée par la formation ?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1, verbose_name="Priorité d'apprentissage"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reg_date',
            field=models.DateField(default=datetime.date.today, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='learningcourse',
            name='employee',
            field=models.ManyToManyField(related_name='courses', to='employee_learning.employee', verbose_name='Employés inscrits'),
        ),
        migrations.AlterField(
            model_name='learningcourse',
            name='level',
            field=models.CharField(choices=[('B', 'Basic'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='learningcourse',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du cours'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
